# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81f098aa75f2b80fcd8ac5feb8d351d436fdc1da45aacc8fe3dd3985a80d6cf33f2841dfd104f6157145c06098bc7c8bd4b0273958bc99b839d67a168e178a69

test:
  secret_key_base: 296c149dd4c88ab9d9f22caf2c1f2936c6f7f11f362f439176024384ffb3d662c6222cf17999da35798697ff7919dfc780e0a6b22aba855dc800074304594920

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
